# This notebook pre-processes tweets

### It does the following:
1. Removes records whose tweet text is reduced to less than 4 words because sentiment cannot be absorbed

In [1]:
import pandas as pd
import nltk
from nltk import word_tokenize, sent_tokenize, FreqDist
from nltk.corpus import stopwords
from nltk.corpus import words
from nltk.stem import LancasterStemmer, WordNetLemmatizer
from nltk.tokenize.treebank import TreebankWordDetokenizer
from nltk.tokenize import TweetTokenizer
import re
import threading
import langdetect as ld
from nltk.corpus import words
import numpy as np
import shutil

In [4]:
tweet_data = pd.read_csv("../datasets/general/preprocessed_tweets.csv")

C:\Users\dell\Anaconda3\envs\fyp\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
tweet_data

,Unnamed: 0,Unnamed: 0.1,index,id,user,fullname,url,timestamp,replies,likes,retweets,text
0,0,1,1,1.132977e+18,bitcointe,Bitcointe,NaN,2019-05-27 11:49:18+00,0.0,0.0,0.0,Cardano Digitize Currencies EOS 6500 ROI AT T ...
1,1,2,2,1.132977e+18,3eyedbran,Bran - 3 Eyed Raven,NaN,2019-05-27 11:49:06+00,0.0,2.0,1.0,Another Test tweet that wasnt caught stream bi...
2,2,3,3,1.132977e+18,DetroitCrypto,J. Scardina,NaN,2019-05-27 11:49:22+00,0.0,0.0,0.0,Current Crypto Prices BTC 872199 USD ETH 26662...
3,3,4,4,1.132977e+18,mmursaleen72,Muhammad Mursaleen,NaN,2019-05-27 11:49:23+00,0.0,0.0,0.0,Spiv Nosar Baz BITCOIN Is An Asset NOT A Currency
4,4,6,6,1.132977e+18,evilrobotted,evilrobotted,NaN,2019-05-27 11:49:25+00,0.0,0.0,0.0,USER We have been building on real SV What hav...
...,...,...,...,...,...,...,...,...,...,...,...,...
11912995,11908,15638947,20165006,1.198261e+18,iceXzi,iceXzi,NaN,2019-11-23 15:24:08+00,17.0,20.0,24.0,200 or giveaway 1 RT this tweet 2 Follow ME 3 ...
11912996,11909,15638948,20165007,1.198266e+18,digital_mine_,digital mine ‚ö°ü§ñüë®‚Äçüíªüá≠üá∞üá≠üá∞üá≠üá∞,NaN,2019-11-23 15:45:55+00,0.0,0.0,0.0,Daily profit for HODLING BTC since 2013 Data t...
11912997,11910,15638949,20165008,1.198262e+18,JacobCanfield,Jacob Canfield,NaN,2019-11-23 15:28:50+00,2.0,16.0,3.0,Happy A while back I created new set of Fibona...
11912998,11911,15638951,20165010,1.198266e+18,torusJKL,Gal Buki ($torusJKL),NaN,2019-11-23 15:45:56+00,0.0,0.0,0.0,Register now for early access of Codugh API ma...
11912999,11912,15638952,20165011,1.198266e+18,Adekunl95628158,Adekunle Daniel,NaN,2019-11-23 15:45:57+00,0.0,0.0,0.0,USER USER Do you know that BTC Baskets isnt ba...

In [11]:
def count_words(sentence):
    sentence = str(sentence)
    return len(sentence.split())

In [12]:
#remove tweets with less than 3 tweets
tweet_data = tweet_data[tweet_data['text'].map(count_words) > 3]

In [15]:
#delete folder with tweets which was used for preprocessing
shutil.rmtree("./../datasets/cleaned_tweets")

In [14]:
tweet_data.to_csv("./../datasets/general/tweets_cleaned.csv")